### PR TITLE
Fix(Sura): Transparent pixels in sura dividers.

### PR DESCRIPTION
**Pull request by a0m0rajab**

### CODE REVIEW

**Comment by maeyler** [comment]
Zoom için kullandığım büyüteç (*magnifier icon*) arama (*search*) anlamına
geliyor. Ekteki simgeyi kullanmak istedim ama yapamadım.

Transparent pixel nasıl yapılır?


On Wed, Feb 10, 2021

> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/Okuyun/Kuran/pull/6
> Commit Summary
>
>    - Fix(Sura): Transparent pixels in sura dividers.
>
> File Changes
>
>    - *M* image/sura.png
>    <https://github.com/Okuyun/Kuran/pull/6/files#diff-25fc6dcb8d5a465f9f949fe170f5217d92ecf81868a97e7b29b8e6b95bd46048>
>    (0)
>
>

**Comment by a0m0rajab** [comment]
Transparent pixel için Gimp kullandım.

**Review by maeyler — COMMENTED** [review]
Two problems observed after accepting the PR:
* "not found" message whenever language is changed
* "not found" message is too large

**Reverting to Commit #ced3067 on March 2**

**Comment by maeyler** [comment]
The review above is related to Rehber -- cannot delete

**Pull request merged**
